variables:
  GIT_SUBMODULE_STRATEGY: recursive

pages:
  stage: deploy
  script:
    - mkdir .public
    - cp -r * .public
    - rm .public/deploy.py
    - mv .public public
  artifacts:
    paths:
      - public
  only:
    - master
